name = "Git Test Site (Again: The Threequel)"
type = 1
source = "https://github.com/CStafford-14/hpt.git"
owner = "System"
version = 1
image = "http://upload.wikimedia.org/wikipedia/commons/8/86/Wood.duck.arp.jpg"
color = "#000055"
id = "242b94ac-a7a4-4c87-822d-dd1fe288e2b6"
